---
##########################
# versions

ceph_version: pacific
manager_version: latest
openstack_version: xena

##########################
# celery

celery_enable: true

##########################
# ara

ara_enable: true
ara_server_database_type: sqlite3
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# netbox

netbox_enable: true
netbox_api_url: "http://192.168.10.16:1080/netbox"

##########################
# configuration

configuration_directory: /opt/configuration

configuration_type: git
configuration_git_version: main
configuration_git_host: github.com
configuration_git_port: 443
configuration_git_repository: parduengo/osism-vmbox.git
configuration_git_protocol: https

##########################
# NOTE: Workaround to be able to use Zun in AIO installation

api_address_family: ipv4
api_interface: "{{ internal_interface }}"
