---
node_id: 10

netdata_host_type: server

netbox_inventory_tags:
  - ceph-control
  - ceph-resource
  - compute
  - control
  - generic
  - manager
  - monitoring
  - network

# NOTE: Workaround to be able to use Zun in AIO installation
etcd_client_port: 2379
