---
##########################
# docker

docker_version: "5:20.10.6"
docker_zun: true

##########################
# docker registries

ceph_docker_registry: quay.io
docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# operator

operator_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIquLz7xZ1rzpsoivjOiZTarg+jri0ezRn823wGw4G0gFfosxPxNJ4BS1LaGjje9YI4JVsU2btDuxcNIvmRehVLPHxRwpDHE+FVajltnF1DQXiySitdbC27N1NIaVbWv8y1C2PFnXL+QUrF2VddOzNnMBXingEV2Ev/bTW/XfVTTArpHsNTS0DJRMpMeUROHmCwxhWjjuFfCcH2EEn5KyBCvgiQIozkwf5Q7nK3DeG2QODxtLPJkmCEuvpqbwZF8VkaE1n1TLr7a9CD/p4sn1+Z1BJO+Zsg72AM9A0lKQ0/1TCsAHLMIoZoNH2F7JeNtApFhDAEg9EZGyk0RDkrKxojYzuimvoyYXI84JDdKx3kDFGiXB3ITDMOFRajGLdgJwAZT2Aw62H0uWQs1dMNRtMgaemLIDmschZDVH5j9iDwEZaKVzJ6LLDSn1Wl09nuZNV8okNIvsBe4X6mHzqwLOYYga/HmI6y4nudTLSeckFraMXGRFFfGHDVpNwKRRavx0= dragon@osism

##########################
# resolvconf

resolvconf_nameserver:
  - 8.8.8.8
  - 9.9.9.9
resolvconf_search: testbed.osism.xyz
resolvconf_dnssec: false

##########################
# hosts

hosts_type: template
hosts_additional_entries:
  api.testbed.osism.xyz: 192.168.16.254

##########################
# common

cleanup_services_extra:
  - NetworkManager
  - iscsid
  - lxcfs
  - nscd
  - ntp

##########################
# kolla

kolla_internal_vip_address: 192.168.16.254

##########################
# serial

osism_serial_default: 100%
osism_serial:
  docker: 100%

##########################
# ceph

ceph_share_directory: /share
ceph_cluster_fsid: 11111111-1111-1111-1111-111111111111
