---
##########################################################
# ansible

ansible_python_interpreter: /usr/bin/python3
ansible_host: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}"
