---
##########################################################
# generic

internal_address: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}"
internal_interface: "{{ network_mgmt_interface }}"

console_interface: "{{ internal_interface }}"
management_interface: "{{ internal_interface }}"

##########################################################
# netbox

netbox_inventory_status: Active
netbox_inventory_device_role: generic
