---
##########################################################
# ansible

ansible_python_interpreter: /usr/bin/python3
ansible_host: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}"

##########################################################
# generic

internal_address: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}"
internal_interface: "{{ network_mgmt_interface }}"

console_interface: "{{ internal_interface }}"
management_interface: "{{ internal_interface }}"

##########################################################
# netbox

netbox_inventory_status: Active
netbox_inventory_device_role: generic

##########################################################
# network

network_mgmt_interface: enp0s3
network_workload_interface: enp0s8

network_type: netplan

network_mgmt_address: "{{ network_mgmt_network | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}"
network_mgmt_mtu: 1500
network_mgmt_network: "192.168.16.0/20"
network_mgmt_network_subnet_mask: "20"  # NOTE: This should be obtained via ipaddr filter over mgmt_network

network_ethernets:
  "{{ network_mgmt_interface }}":
    addresses:
      - "{{ network_mgmt_network | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}/{{ network_mgmt_network_subnet_mask }}"
    gateway4: "{{ network_mgmt_network | ipaddr('net') | ipaddr('1') | ipaddr('address') }}"
  "{{ network_workload_interface }}": {}

network_vlans:
  vlan100:
    id: 100
    link: "{{ network_mgmt_interface }}"
    addresses:
      - "192.168.100.{{ node_id }}/24"
  vlan101:
    id: 101
    link: "{{ network_mgmt_interface }}"
    addresses:
      - "192.168.101.{{ node_id }}/24"
  vlan102:
    id: 102
    link: "{{ network_mgmt_interface }}"
    addresses:
      - "192.168.102.{{ node_id }}/24"
