---
global:
  resolve_timeout: 5m

route:
  receiver: default-receiver
  group_by: [alertname, datacenter, app]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: default-receiver
